[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["DEADBLACKCLOVER <deadblackclover@protonmail.com>"]
description = "A sample project with wasm-pack"
edition = "2018"

[dependencies]

[lib]
crate-type =["cdylib"]
